name: transit_pro
description: "Student Transport Management App - Safe Journeys, Happy Kids, Peace of Mind"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.9

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.0.0
  image_picker: ^1.1.2
  url_launcher: ^6.3.0
    
dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^6.0.0
  
flutter:
  uses-material-design: true
  assets:
    - assets/images/navbar/
    - assets/images/profile/
    - assets/images/profile_page/
    - assets/images/role_selection/
    - assets/images/schedule/
    - assets/images/splash_screen/bus_splash_icon.png
    - assets/images/stats/
    - assets/images/utilities/
    - assets/images/
    - assets/images/notification_bell.gif
    - assets/images/path_transparent.gif
