import 'package:flutter/material.dart';

/// Singleton ChangeNotifier that manages app language (English / Urdu).
class LanguageProvider extends ChangeNotifier {
  static final LanguageProvider instance = LanguageProvider._();
  LanguageProvider._();

  String _lang = 'English'; // 'English' | 'Urdu'

  String get lang => _lang;
  bool get isUrdu => _lang == 'Urdu';

  void setLanguage(String language) {
    if (_lang == language) return;
    _lang = language;
    notifyListeners();
  }
}

// ----------------------------------------------------------- Strings ----------

class AppStrings {
  AppStrings._();

  static String t(String key) {
    final isUrdu = LanguageProvider.instance.isUrdu;
    return isUrdu ? (_ur[key] ?? _en[key] ?? key) : (_en[key] ?? key);
  }

  static final Map<String, String> _en = {
    // Navbar
    'nav_home': 'Home',
    'nav_track': 'Track',
    'nav_schedule': 'Schedule',
    'nav_alerts': 'Alerts',
    'nav_fees': 'Fees',
    'nav_profile': 'Profile',

    // Dashboard
    'good_morning': 'Good Morning',
    'good_afternoon': 'Good Afternoon',
    'good_evening': 'Good Evening',
    'no_children_yet': 'No children added yet',
    'on_the_bus': 'On the Bus',
    'to_school': 'to school',
    'todays_schedule': 'Today\'s Schedule',
    'view_all': 'View All',
    'recent_alerts': 'Recent Alerts',
    'estimated_arrival': 'ESTIMATED ARRIVAL',
    'arrival_time': 'ARRIVAL TIME',
    'pickup': 'Pickup',
    'at_school': 'At School',
    'drop_off': 'Drop Off',
    'done': 'Done',
    'pending': 'Pending',
    'total_trips': 'Total Trips',
    'on_time': 'On-Time',
    'this_week': 'This Week',
    'safe_rides': 'Safe Rides',
    'min': 'min',
    'currently_at': 'Currently at',
    'bus_approaching': 'Bus approaching your stop in 8 min',

    // Profile
    'edit_info': 'Edit Info',
    'add_child': 'Add Child',
    'children_section': 'CHILDREN',
    'no_children_added':
        'No children added yet.\nTap "Add Child" to get started.',
    'notification_prefs': 'NOTIFICATION PREFERENCES',
    'boarding_alerts': 'Boarding Alerts',
    'boarding_alerts_desc': 'When your child boards/exits',
    'arrival_notifs': 'Arrival Notifications',
    'arrival_notifs_desc': 'School & home arrivals',
    'delay_alerts': 'Delay Alerts',
    'delay_alerts_desc': 'When bus is late',
    'sms_notifs': 'SMS Notifications',
    'sms_notifs_desc': 'Text message alerts',
    'email_notifs': 'Email Notifications',
    'email_notifs_desc': 'Daily summary email',
    'trip_history': 'Trip History',
    'trip_history_desc': '142 completed trips',
    'subscription': 'Subscription',
    'emergency_contacts': 'Emergency Contacts',
    'emergency_contacts_desc': '2 contacts added',
    'change_password': 'Change Password',
    'language': 'Language',
    'help_support': 'Help & Support',
    'rate_app': 'Rate the App',
    'dark_mode': 'Dark Mode',
    'light_mode': 'Light Mode',
    'log_out': 'Log Out',
    'remove_child': 'Remove Child',
    'cancel': 'Cancel',
    'remove': 'Remove',
    'edit_my_info': 'Edit My Information',
    'full_name': 'Full Name',
    'email': 'Email',
    'phone': 'Phone',
    'child_s_info': 'Edit Info',
    'save': 'Save',
    'plan_active': 'Plan � Active',
    'add_new_child': 'Add New Child',
    'child_name': 'Child Name',
    'grade': 'Grade',
    'school': 'School',
    'route': 'Route',
    'bus_stop': 'Bus Stop',
    'driver_name': 'Driver Name',
    'remove_child_confirm': 'Remove {name} from your account?',
    'this_child': 'this child',
    'edit_child_info': "Edit {name}'s Info",

    // Tracking
    'live_tracking': 'Live Tracking',
    'live': 'LIVE',
    'route_map': 'Route Map',
    'route_stops': 'Route Stops',
    'bus_information': 'Bus Information',
    'driver': 'Driver',
    'bus_number': 'Bus Number',
    'speed': 'Speed',
    'students': 'Students',
    'completed': 'Completed',
    'current': 'Current',
    'upcoming': 'Upcoming',

    // Schedule
    'schedule': 'Schedule',
    'morning_pickup': 'MORNING PICKUP',
    'evening_drop': 'EVENING DROP',
    'route_a_timetable': 'Route A Timetable',
    'stop': 'STOP',
    'morning': 'MORNING',
    'evening': 'EVENING',
    'upcoming_holidays': 'Upcoming Holidays',
    'oak_street_stop': 'Oak Street Stop',
    'active': '? Active',
    'completed_check': 'Completed',
    'upcoming_clock': 'Upcoming',

    // Notifications
    'notifications': 'Notifications',
    'mark_all_read': 'Mark all read',
    'all': 'All',
    'unread': 'Unread',
    'today': 'Today',
    'alerts': 'Alerts',
    'no_notifs': 'No notifications in this category',

    // Fees
    'my_fees': 'My Fees',
    'fee_details': 'Transport fee details & payments',
    'outstanding_balance': 'Outstanding Balance',
    'pay_now': 'Pay Now',
    'paid': 'Paid',
    'total': 'Total',
    'payment_history': 'Payment History',
    'fee_breakdown': 'Fee Breakdown (Annual)',
    'transport_fee': 'Transport Fee',
    'maintenance_levy': 'Maintenance Levy',
    'insurance': 'Insurance',
    'id_card_fee': 'ID Card Fee',
    'gps_tracking': 'GPS Tracking',
    'overdue': 'Overdue',

    // Help & Support
    'help_and_support': 'Help & Support',
    'app_language': 'App Language',
    'choose_language': 'Choose your preferred language',
    'email_us': 'Email Us',
    'call_us': 'Call Us',
    'live_chat': 'Live Chat',
    'live_chat_hours': 'Mon�Fri\n9am�6pm',
    'faq': 'Frequently Asked Questions',
    'send_message': 'Send a Message',
    'subject': 'Subject',
    'describe_issue': 'Describe your issue...',
    'chat_online_status': 'TransitPro Support � Online',
    'type_message': 'Type your message�',
    'send': 'Send Message',
    'message_sent': "Message sent! We'll reply within 24h.",

    // Change Password
    'change_password_title': 'Change Password',
    'update_password': 'Update your password',
    'strong_password': 'Use a strong password with at least 8 characters.',
    'current_password': 'Current Password',
    'new_password': 'New Password',
    'confirm_new_password': 'Confirm New Password',
    'password_requirements': 'Password Requirements',
    'min_8_chars': 'At least 8 characters',
    'uppercase': 'One uppercase letter',
    'one_digit': 'One number',
    'special_char': 'One special character (!@#\$...)',
    'pwd_strength': 'Password Strength',
    'pwd_weak': 'Weak',
    'pwd_fair': 'Fair',
    'pwd_good': 'Good',
    'pwd_strong': 'Strong',
    'passwords_match': 'Passwords match',
    'update_password_btn': 'Update Password',
    'fill_all_fields': 'Please fill in all fields',
    'pwd_not_meet': 'New password does not meet requirements',
    'pwd_no_match': 'Passwords do not match',
    'pwd_changed': 'Password changed successfully',

    // Emergency Contacts
    'emergency_contacts_title': 'Emergency Contacts',
    'add_contact': 'Add Contact',
    'edit_contact': 'Edit Contact',
    'relation': 'Relation (e.g. Mother)',
    'phone_number': 'Phone Number',
    'no_emergency_contacts': 'No emergency contacts added',
    'remove_contact': 'Remove Contact',
    'emergency_contact_fallback': 'Emergency Contact',
    'add_one_now': 'Add one now',
    'trip_history_title': 'Trip History',
    'trips_this_month': 'trips this month',
    'on_time_rate': 'on-time rate',
    'duration': 'duration',
    'delayed': 'Delayed',
    'afternoon': 'Afternoon',
    'morning_filter': 'Morning',
    'all_filter': 'All',
    'this_week_filter': 'This Week',
    'trips_lbl': 'trips',

    // Rate App
    'rate_app_title': 'Rate the App',
    'enjoying_transitpro': 'Enjoying TransitPro?',
    'feedback_helps':
        'Your feedback helps us improve\nthe experience for everyone.',
    'how_do_you_feel': 'How do you feel about\nTransitPro?',
    'write_review': 'Write a review (optional)',
    'leave_comment': 'Leave a comment (optional)',
    'tell_us_what': 'Tell us what you think...',
    'review_hint': 'Share your experience...',
    'submit_rating': 'Submit Rating',
    'submit_review': 'Submit Review',
    'thank_you': 'Thank You!',
    'review_submitted': 'Your feedback helps us improve',
    'you_rated': 'You rated us {stars} star{plural}.',
    'better_app': 'Your feedback helps us build a\nbetter app for all parents.',
    'back_to_profile': 'Back to Profile',
    'star_poor': 'Poor',
    'star_fair': 'Fair',
    'star_good': 'Good',
    'star_very_good': 'Very Good',
    'star_excellent': 'Excellent',

    // Subscription
    'subscription_title': 'Subscription',
    'current_plan': 'Current Plan',
    'available_plans': 'AVAILABLE PLANS',
    'change_plan': 'Change Plan',
    'switch_plan': 'Switch Plan',
    'best_value': 'Best Value',
    'current_badge': 'Current',
    'active_renews': 'Active · Renews Apr 8, 2026',

    // Language
    'language_title': 'Language',
    'apply': 'Apply',
    'language_set': 'Language set to',

    // Role Selection
    'welcome_banner': 'WELCOME TO TRANSIT PRO',
    'select_role': 'Select your role',
    'parent_label': "I'm a Parent",
    'parent_desc': "Monitor your child's school commute in real-time",
    'driver_label': "I'm a Driver",
    'driver_desc': 'Manage your route, students & daily schedule',
    'student_label': "I'm a Student",
    'student_desc': 'View bus schedule, track ride & manage fees',
    'no_account': "Don't have an account? ",
    'sign_up': 'Sign Up',
    'data_secure': 'Your data is encrypted & secure',

    // Login
    'back': 'Back',
    'use_demo': 'USE DEMO ACCOUNT',
    'email_address': 'EMAIL ADDRESS',
    'email_hint': 'Enter your email',
    'password_lbl': 'PASSWORD',
    'password_hint': 'Enter your password',
    'forgot_password': 'Forgot password?',
    'login_encrypted': '256-bit encrypted � GDPR compliant',
    'fill_fields_login': 'Please fill in all fields.',
    'parent_login_title': 'Parent Login',
    'parent_login_sub': "Access your child's journey",
    'driver_login_title': 'Driver Login',
    'driver_login_sub': 'Start your route today',
    'student_login_title': 'Student Login',
    'student_login_sub': 'Track your bus & attendance',
    'signin_as_parent': 'Sign In as Parent',
    'signin_as_driver': 'Sign In as Driver',
    'signin_as_student': 'Sign In as Student',
    'parent_role_name': 'Parent',
    'driver_role_name': 'Driver',
    'student_role_name': 'Student',
    'parent_details_title': 'Parent Details',
    'driver_details_title': 'Driver Details',
    'student_details_title': 'Student Details',

    // Signup
    'create_account': 'Create Account',
    'select_role_to_start': 'Select your role to get started',
    'fill_info': 'Fill in your information below',
    'already_account': 'Already have an account? ',
    'sign_in': 'Sign In',
    'select_your_role_lbl': 'SELECT YOUR ROLE',
    'continue_btn': 'Continue',
    'full_name_lbl': 'FULL NAME',
    'enter_full_name': 'Enter your full name',
    'enter_email': 'Enter your email',
    'phone_lbl': 'PHONE NUMBER',
    'enter_phone': 'Enter your phone number',
    'confirm_password_lbl': 'CONFIRM PASSWORD',
    'create_password_hint': 'Create a password',
    'reenter_password_hint': 'Re-enter your password',
    'agree_terms': 'I agree to the Terms of Service & Privacy Policy',
    'create_account_btn': 'Create Account',
    'add_another_child': 'Add Another Child',
    'childs_name_lbl': "CHILD'S NAME",
    'childs_name_hint': "Child's full name",
    'grade_level_lbl': 'GRADE / LEVEL',
    'select_level_hint': 'Select level',
    'school_institution_lbl': 'SCHOOL / INSTITUTION',
    'license_number_lbl': 'LICENSE NUMBER',
    'enter_license_hint': 'Enter your driving license number',
    'vehicle_number_lbl': 'VEHICLE NUMBER',
    'vehicle_number_hint': 'e.g. BUS-42',
    'vehicle_type_lbl': 'VEHICLE TYPE',
    'select_type_hint': 'Select type',
    'experience_yrs_lbl': 'EXPERIENCE (YRS)',
    'student_id_lbl': 'STUDENT ID',
    'student_id_hint': 'e.g. STU-1234',
    'email_address_lbl': 'EMAIL ADDRESS',
    'details_lbl': 'Details',
    'child_lbl': 'Child',
    'search_school_hint': 'Search school / institution…',
    'experience_hint': 'e.g. 5',

    // Forgot Password
    'forgot_password_title': 'Forgot Password?',
    'check_email_title': 'Check Your Email',
    'forgot_pass_sub':
        "Enter your email and we'll send you\na link to reset your password",
    'check_email_sub':
        "We sent a reset link to your email.\nPlease check your inbox.",
    'send_reset': 'Send Reset Link',
    'reset_sent': 'Reset link sent successfully!\nPlease check your inbox.',
    'back_to_login': 'Back to Login',

    // Welcome screen
    'safe_journeys': 'Safe Journeys � Happy Kids � Peace of Mind',
    'pill_tracking': 'Live Tracking',
    'pill_alerts': 'Alerts',
    'pill_safe': 'Safe & Secure',

    // Driver navbar
    'dnav_home': 'Home',
    'dnav_students': 'Students',
    'dnav_route': 'Route',
    'dnav_alerts': 'Alerts',
    'dnav_profile': 'Profile',

    // Student navbar
    'snav_home': 'Home',
    'snav_track': 'Track',
    'snav_schedule': 'Schedule',
    'snav_qr': 'QR Pass',
    'snav_fees': 'Fees',
    'snav_profile': 'Profile',

    // Driver dashboard
    'todays_route': "TODAY'S ROUTE",
    'in_progress_badge': 'IN PROGRESS',
    'not_started_badge': 'NOT STARTED',
    'route_progress': 'Route Progress',
    'stops_done': 'Stops Done',
    'time_left': 'Time Left',
    'next_stop': 'NEXT STOP',
    'quick_actions': 'Quick Actions',
    'emergency': 'Emergency',
    'alert_all': 'Alert All',
    'share_location': 'Share Location',
    'update_route': 'Update Route',
    'todays_stats': "Today's Stats",
    'students_picked': 'Students Picked Up',
    'route_completion': 'Route Completion',
    'on_time_perf': 'On-Time Performance',
    'start_route': 'Start Route',
    'end_route': 'End Route',

    // Driver attendance
    'student_attendance': 'Student Attendance',
    'boarding_progress': 'Boarding Progress',
    'boarded': 'Boarded',
    'absent': 'Absent',
    'search_student': 'Search student or stop...',

    // Driver route
    'route_navigator': 'Route Navigator',
    'live_route_map': 'Live Route Map',
    'eta_school': 'ETA School',
    'distance_left': 'Distance Left',
    'avg_speed': 'Avg Speed',

    // Driver notifications
    'messages': 'Messages',
    'parents_tab': 'Parents',
    'admin_tab': 'Admin',
    'system_tab': 'System',
    'reply': 'REPLY',
    'type_reply': 'Type your reply...',

    // Driver profile
    'driver_info_section': 'DRIVER INFORMATION',
    'license_no_lbl': 'License No.',
    'experience_lbl': 'Experience',
    'bus_number_lbl': 'Bus Number',
    'route_lbl': 'Route',
    'mobile_lbl': 'Mobile',
    'total_students_lbl': 'Total Students',
    'bus_info_section': 'BUS INFORMATION',
    'capacity_lbl': 'Capacity',
    'fuel_lbl': 'Fuel',
    'last_service_lbl': 'Last Service',
    'app_settings': 'APP SETTINGS',
    'active_on_route': 'Active � On Route',
    'settings': 'Settings', 'share_loc_desc': 'Parents can see bus location',
    'parent_alerts_lbl': 'Parent Auto-Alerts',
    'parent_alerts_desc': 'Send boarding notifications',
    'route_reminders_lbl': 'Route Reminders',
    'route_reminders_desc': '10 min before each stop',
    'break_alerts_lbl': 'Break Notifications',
    'break_alerts_desc': 'Alert for scheduled breaks',
    'performance_report': 'Performance Report',
    'performance_report_desc': '96% on-time rate',
    'documents_license': 'Documents & License',
    'documents_license_desc': 'All verified \u2713',
    // Student dashboard
    'my_qr_pass': 'My QR Pass',
    'show_qr': 'Show QR for check-in/check-out',
    'total_rides': 'Total Rides',

    // Student tracking
    'track_my_bus': 'Track My Bus',
    'live_map_view': 'Live Map View',
    'gps_tracking_here': 'GPS tracking will appear here',
    'distance': 'Distance',
    'stops_left': 'Stops Left',

    // Student schedule
    'my_schedule': 'My Schedule',
    'pickup_dropoff_timings': 'Pickup & drop-off timings',
    'morning_pickup_s': 'Morning Pickup',
    'afternoon_dropoff_s': 'Afternoon Drop-off',
    'be_at_stop': 'Be at Stop',
    'bus_arrives': 'Bus Arrives',
    'qr_checkin': 'QR Check-in',
    'reach_school': 'Reach School',
    'school_dismissal': 'School Dismissal',
    'qr_checkout': 'QR Check-out',
    'bus_departs': 'Bus Departs',
    'reach_stop': 'Reach Stop',
    'this_week_summary': 'This Week Summary',
    'checkins_lbl': 'Check-ins',
    'active_status': 'Active',
    'your_stop': 'Your Stop',
    'day_mon': 'Mon',
    'day_tue': 'Tue',
    'day_wed': 'Wed',
    'day_thu': 'Thu',
    'day_fri': 'Fri',
    'day_sat': 'Sat',

    // Student attendance (QR)
    'qr_pass': 'QR Pass',
    'show_pass_checkin': 'Show your pass for check-in & check-out',
    'monthly_report': 'Monthly Report',
    'total_checkins': 'Total\nCheck-ins',

    // Student fees
    'my_fees_s': 'My Fees',
    'fee_details_s': 'Transport fee details & payments',
    'outstanding_balance_s': 'Outstanding Balance',

    // Student profile
    'transport_details': 'Transport Details',
    'driver_phone_lbl': 'Driver Phone',
    'parent_guardian_lbl': 'Parent / Guardian',
    'bus_lbl': 'Bus',
    'stop_lbl': 'Stop',
    'driver_lbl': 'Driver',
    'name_lbl': 'Name',
    'rides_lbl': 'Rides',
    'settings_lbl': 'Settings',
    'notifications_lbl': 'Notifications',
    'appearance_lbl': 'Appearance',
    'privacy_lbl': 'Privacy',
    'terms_lbl': 'Terms of Service',
    'log_out_text': 'Log Out',

    // FAQ
    'faq_q1': 'How do I track my child\'s bus in real time?',
    'faq_a1':
        'Go to the "Live Tracking" tab from the bottom navigation bar. The map will show the bus\'s current position and estimated arrival time at each stop.',
    'faq_q2': 'How do I add another child to my account?',
    'faq_a2':
        'Open the Profile tab, scroll to the Children section, and tap the "+" button. Fill in your child\'s name, grade, school and bus details.',
    'faq_q3': 'Why am I not receiving notifications?',
    'faq_a3':
        'Make sure notifications are enabled for TransitPro in your device Settings. You can also check alert preferences inside App Settings on the Profile tab.',
    'faq_q4': 'How do I update my child\'s bus route?',
    'faq_a4':
        'Tap the child card on the Profile tab, then select "Edit Info". Update the Bus Number, Route, or Stop fields and tap Save.',
    'faq_q5': 'How do I change my emergency contacts?',
    'faq_a5':
        'Go to Profile → Emergency Contacts. You can add, edit or remove contacts from there.',
    'faq_q6': 'What does the Premium plan include?',
    'faq_a6':
        'Premium includes live GPS tracking, up to 3 child profiles, push & SMS alerts, full trip history and emergency contact management.',

    // Subscription plan features
    'plan_premium_name': 'Premium',
    'plan_family_name': 'Family',
    'plan_basic_name': 'Basic',
    'feat_live_gps': 'Live GPS tracking',
    'feat_3_profiles': 'Up to 3 child profiles',
    'feat_push_sms': 'Push + SMS alerts',
    'feat_trip_history': 'Full trip history',
    'feat_emergency': 'Emergency contacts',
    'feat_everything_premium': 'Everything in Premium',
    'feat_unlimited_profiles': 'Unlimited child profiles',
    'feat_priority_support': 'Priority support',
    'feat_route_custom': 'Route customisation',
    'feat_driver_chat': 'Driver direct chat',

    // Trip history
    'trip_type_morning_pickup': 'Morning Pickup',
    'trip_type_afternoon_dropoff': 'Afternoon Drop-off',
    'trip_status_on_time': 'On Time',
    'trip_status_5_late': '5 min late',
    'trip_status_1_early': '1 min early',
    'trip_to_arrow': '→',

    // Payment screens
    'select_payment_method': 'Select Payment Method',
    'amount_due': 'Amount Due',
    'month_lbl': 'Month',
    'choose_method': 'Choose Payment Method',
    'cash_payment': 'Cash Payment',
    'cash_payment_desc':
        'Hand cash to your driver and submit a confirmation request.',
    'requires_approval': 'Requires Driver Approval',
    'online_payment': 'Online Transfer',
    'online_payment_desc':
        'Transfer via JazzCash or EasyPaisa to driver\'s account.',
    'card_payment': 'Credit / Debit Card',
    'card_payment_desc': 'Pay securely with Visa or Mastercard.',
    'secure_payment_note': 'All payments are encrypted and secure.',
    'cash_info_banner':
        'Hand the exact amount to your driver. After submitting this request, your driver will confirm receipt on their app.',
    'notes_optional': 'Notes (Optional)',
    'cash_notes_hint': 'e.g. Paid at school gate on 14 Dec...',
    'send_cash_request': 'Submit Cash Payment Request',
    'request_submitted': 'Request Submitted!',
    'cash_request_submitted_desc':
        'Your driver has been notified. They will confirm once you hand over the cash.',
    'amount_lbl': 'Amount',
    'request_id_lbl': 'Request ID',
    'status_lbl': 'Status',
    'pending_driver_confirmation': 'Pending Driver Confirmation',
    'back_to_fees': 'Back to Fees',
    'payment_method_lbl': 'Method',
    'select_child': 'Select Child',
    'select_platform': 'Select Platform',
    'driver_account_details': 'Driver Account Details',
    'platform_not_available':
        'This platform is not available for your driver. Please use the other option.',
    'enter_transaction_id': 'Enter Transaction ID',
    'txn_id_hint': 'e.g. TXN1234567890',
    'confirm_payment': 'I\'ve Paid — Confirm',
    'payment_submitted': 'Payment Submitted!',
    'online_submitted_desc':
        'Your transaction has been recorded. The driver will verify the transfer.',
    'transaction_id_lbl': 'Transaction ID',
    'platform_lbl': 'Platform',
    'driver_account': 'Driver Account',
    'driver_name_lbl': 'Driver',
    'account_name_lbl': 'Account Name',
    'account_number_lbl': 'Account Number',
    'bus_lbl': 'Bus',
    'send_exactly': 'Send exactly:',
    'copied': 'Copied!',
    'card_number_lbl': 'Card Number',
    'expiry_lbl': 'Expiry Date',
    'cvv_lbl': 'CVV',
    'cardholder_name': 'Cardholder Name',
    'name_on_card_hint': 'As printed on card',
    'invalid_card_number': 'Enter a valid 16-digit card number',
    'invalid_expiry': 'Enter a valid expiry (MM/YY)',
    'invalid_cvv': 'Enter a valid CVV',
    'enter_card_name': 'Enter cardholder name',
    'processing': 'Processing...',
    'pay': 'Pay',
    'ssl_secured': 'SSL encrypted · 256-bit security',
    'payment_successful': 'Payment Successful!',
    'card_success_desc': 'Your payment has been processed successfully.',
    'card_lbl': 'Card',
    'approved': 'Approved',
    'amount_to_pay': 'Amount to Pay',
    'card_name_lbl': 'CARD HOLDER',
  };

  static final Map<String, String> _ur = {
    // Navbar
    'nav_home': 'ہوم',
    'nav_track': 'ٹریک',
    'nav_schedule': 'شیڈول',
    'nav_alerts': 'الرٹس',
    'nav_fees': 'فیس',
    'nav_profile': 'پروفائل',

    // Dashboard
    'good_morning': 'صبح بخیر',
    'good_afternoon': 'سہ پہر بخیر',
    'good_evening': 'شام بخیر',
    'no_children_yet': 'ابھی تک کوئی بچہ شامل نہیں کیا گیا',
    'on_the_bus': 'باصلاحیت بس پر ہے',
    'to_school': 'اسکول کے لیے',
    'todays_schedule': 'آج کا شیڈول',
    'view_all': 'تمام دیکھیں',
    'recent_alerts': 'حالیہ الرٹس',
    'estimated_arrival': 'متوقع آمد',
    'arrival_time': 'آمد کا وقت',
    'pickup': 'پک اپ',
    'at_school': 'اسکول میں',
    'drop_off': 'ڈراپ آف',
    'done': 'مکمل',
    'pending': 'زیر التواء',
    'total_trips': 'کل سفر',
    'on_time': 'وقت پر',
    'this_week': 'اس ہفتے',
    'safe_rides': 'محفوظ سفر',
    'min': 'منٹ',
    'currently_at': 'اس وقت یہاں ہے',
    'bus_approaching': 'بس 8 منٹ میں آپ کے اسٹاپ پر پہنچ رہی ہے',

    // Profile
    'edit_info': 'معلومات تبدیل کریں',
    'add_child': 'بچہ شامل کریں',
    'children_section': 'بچے',
    'no_children_added':
        'ابھی تک کوئی بچہ شامل نہیں کیا گیا۔\nشروع کرنے کے لیے "بچہ شامل کریں" پر کلک کریں۔',
    'notification_prefs': 'اطلاعات کی ترجیحات',
    'boarding_alerts': 'سوار ہونے کے الرٹس',
    'boarding_alerts_desc': 'جب آپ کا بچہ بس میں سوار ہو یا اترے',
    'arrival_notifs': 'آمد کی اطلاعات',
    'arrival_notifs_desc': 'اسکول اور گھر آمد',
    'delay_alerts': 'تاخیر کے الرٹس',
    'delay_alerts_desc': 'جب بس لیٹ ہو',
    'sms_notifs': 'ایس ایم ایس اطلاعات',
    'sms_notifs_desc': 'ٹیکسٹ میسج الرٹس',
    'email_notifs': 'ای میل اطلاعات',
    'email_notifs_desc': 'روزانہ خلاصہ ای میل',
    'trip_history': 'سفر کی تاریخ',
    'trip_history_desc': '142 مکمل شدہ سفر',
    'subscription': 'سبسکرپشن',
    'emergency_contacts': 'ہنگامی رابطے',
    'emergency_contacts_desc': '2 رابطے شامل ہیں',
    'change_password': 'پاس ورڈ تبدیل کریں',
    'language': 'زبان',
    'help_support': 'مدد اور تعاون',
    'rate_app': 'ایپ کی درجہ بندی کریں',
    'dark_mode': 'ڈارک موڈ',
    'light_mode': 'لائٹ موڈ',
    'log_out': 'لاگ آؤٹ',
    'remove_child': 'بچہ ختم کریں',
    'cancel': 'منسوخ کریں',
    'remove': 'ختم کریں',
    'edit_my_info': 'اپنی معلومات تبدیل کریں',
    'full_name': 'پورا نام',
    'email': 'ای میل',
    'phone': 'فون',
    'child_s_info': 'بچے کی معلومات',
    'save': 'محفوظ کریں',
    'plan_active': 'پلان - فعال',
    'add_new_child': 'نیا بچہ شامل کریں',
    'child_name': 'بچے کا نام',
    'grade': 'کلاس',
    'school': 'اسکول',
    'route': 'روٹ',
    'bus_stop': 'بس اسٹاپ',
    'driver_name': 'ڈرائیور کا نام',
    'remove_child_confirm':
        'کیا آپ {name} کو اپنے اکاؤنٹ سے ختم کرنا چاہتے ہیں؟',
    'this_child': 'یہ بچہ',
    'edit_child_info': '{name} کی معلومات تبدیل کریں',

    // Tracking
    'live_tracking': 'لائیو ٹریکنگ',
    'live': 'لائیو',
    'route_map': 'روٹ میپ',
    'route_stops': 'روٹ اسٹاپس',
    'bus_information': 'بس کی معلومات',
    'driver': 'ڈرائیور',
    'bus_number': 'بس نمبر',
    'speed': 'رفتار',
    'students': 'طلباء',
    'completed': 'مکمل',
    'current': 'موجودہ',
    'upcoming': 'آئندہ',

    // Schedule
    'schedule': 'شیڈول',
    'morning_pickup': 'صبح کا پک اپ',
    'evening_drop': 'شام کا ڈراپ',
    'route_a_timetable': 'روٹ اے ٹائم ٹیبل',
    'stop': 'اسٹاپ',
    'morning': 'صبح',
    'evening': 'شام',
    'upcoming_holidays': 'آئندہ تعطیلات',
    'oak_street_stop': 'اوک اسٹریٹ اسٹاپ',
    'active': 'فعال',
    'completed_check': 'مکمل',
    'upcoming_clock': 'آئندہ',

    // Notifications
    'notifications': 'اطلاعات',
    'mark_all_read': 'سب کو پڑھا ہوا قرار دیں',
    'all': 'تمام',
    'unread': 'ان پڑھا',
    'today': 'آج',
    'alerts': 'الرٹس',
    'no_notifs': 'اس کیٹیگری میں کوئی اطلاع نہیں ہے',

    // Fees
    'my_fees': 'میری فیس',
    'fee_details': 'ٹرانسپورٹ فیس کی تفصیلات اور ادائیگیاں',
    'outstanding_balance': 'واجب الادا رقم',
    'pay_now': 'ابھی ادا کریں',
    'paid': 'ادا شدہ',
    'total': 'کل',
    'payment_history': 'ادائیگیوں کی تاریخ',
    'fee_breakdown': 'فیس کی تفصیل (سالانہ)',
    'transport_fee': 'ٹرانسپورٹ فیس',
    'maintenance_levy': 'مینٹیننس چارجز',
    'insurance': 'انشورنس',
    'id_card_fee': 'آئی ڈی کارڈ فیس',
    'gps_tracking': 'جی پی ایس ٹریکنگ',
    'overdue': 'میعاد ختم',

    // Help & Support
    'help_and_support': 'مدد اور تعاون',
    'app_language': 'ایپ کی زبان',
    'choose_language': 'اپنی پسندیدہ زبان منتخب کریں',
    'email_us': 'ہمیں ای میل کریں',
    'call_us': 'ہمیں کال کریں',
    'live_chat': 'لائیو چیٹ',
    'live_chat_hours': 'پیر تا جمعہ\nصبح 9 تا شام 6',
    'faq': 'اکثر پوچھے گئے سوالات',
    'send_message': 'پیغام بھیجیں',
    'subject': 'عنوان',
    'describe_issue': 'اپنے مسئلے کی وضاحت کریں...',
    'chat_online_status': 'ٹرانزٹ پرو سپورٹ - آن لائن',
    'type_message': 'پیغام ٹائپ کریں...',
    'send': 'پیغام بھیجیں',
    'message_sent': 'پیغام بھیج دیا گیا! ہم 24 گھنٹے میں جواب دیں گے۔',

    // Change Password
    'change_password_title': 'پاس ورڈ تبدیل کریں',
    'update_password': 'اپنا پاس ورڈ اپ ڈیٹ کریں',
    'strong_password': 'کم از کم 8 حروف پر مشتمل مضبوط پاس ورڈ استعمال کریں۔',
    'current_password': 'موجودہ پاس ورڈ',
    'new_password': 'نیا پاس ورڈ',
    'confirm_new_password': 'نئے پاس ورڈ کی تصدیق کریں',
    'password_requirements': 'پاس ورڈ کی شرائط',
    'min_8_chars': 'کم از کم 8 حروف',
    'uppercase': 'ایک بڑا حرف (A-Z)',
    'one_digit': 'ایک عدد (0-9)',
    'special_char': 'ایک خاص علامت (!@#\$...)',
    'pwd_strength': 'پاس ورڈ کی مضبوطی',
    'pwd_weak': 'کمزور',
    'pwd_fair': 'مناسب',
    'pwd_good': 'بہتر',
    'pwd_strong': 'مضبوط',
    'passwords_match': 'پاس ورڈ مماثل ہیں',
    'update_password_btn': 'پاس ورڈ اپ ڈیٹ کریں',
    'fill_all_fields': 'براہ کرم تمام خانے پُر کریں',
    'pwd_not_meet': 'نیا پاس ورڈ شرائط پر پورا نہیں اترتا',
    'pwd_no_match': 'پاس ورڈ مماثل نہیں ہیں',
    'pwd_changed': 'پاس ورڈ کامیابی سے تبدیل ہو گیا',

    // Emergency Contacts
    'emergency_contacts_title': 'ہنگامی رابطے',
    'add_contact': 'رابطہ شامل کریں',
    'edit_contact': 'رابطہ تبدیل کریں',
    'relation': 'رشتہ (مثلاً والدہ)',
    'phone_number': 'فون نمبر',
    'no_emergency_contacts': 'کوئی ہنگامی رابطہ شامل نہیں ہے',
    'remove_contact': 'رابطہ ختم کریں',
    'emergency_contact_fallback': 'ہنگامی رابطہ',
    'add_one_now': 'ابھی شامل کریں',
    'trip_history_title': 'سفر کی تاریخ',
    'trips_this_month': 'اس مہینے کے سفر',
    'on_time_rate': 'وقت پر پہنچنے کی شرح',
    'duration': 'دورانیہ',
    'delayed': 'تاخیر',
    'afternoon': 'دوپہر',
    'morning_filter': 'صبح',
    'all_filter': 'سب',
    'this_week_filter': 'اس ہفتے',
    'trips_lbl': 'سفر',

    // Rate App
    'rate_app_title': 'ایپ کی درجہ بندی کریں',
    'enjoying_transitpro': 'ٹرانزٹ پرو کیسا لگ رہا ہے؟',
    'feedback_helps':
        'آپ کی رائے ہمیں سب کے لیے\nتجربہ بہتر بنانے میں مدد دیتی ہے۔',
    'how_do_you_feel': 'آپ ٹرانزٹ پرو کے بارے میں\nکیا محسوس کرتے ہیں؟',
    'write_review': 'جائزہ لکھیں (اختیاری)',
    'leave_comment': 'کمنٹ چھوڑیں (اختیاری)',
    'tell_us_what': 'ہمیں بتائیں کہ آپ کیا سوچتے ہیں...',
    'review_hint': 'اپنا تجربہ شیئر کریں...',
    'submit_rating': 'درجہ بندی جمع کرائیں',
    'submit_review': 'جائزہ جمع کرائیں',
    'thank_you': 'شکریہ!',
    'review_submitted': 'آپ کی رائے ہمیں بہتر بنانے میں مدد دیتی ہے',
    'you_rated': 'آپ نے ہمیں {stars} اسٹار دیے ہیں۔',
    'better_app':
        'آپ کی رائے ہمیں والدین کے لیے\nبہتر ایپ بنانے میں مدد دیتی ہے۔',
    'back_to_profile': 'پروفائل پر واپس جائیں',
    'star_poor': 'ناقص',
    'star_fair': 'مناسب',
    'star_good': 'اچھا',
    'star_very_good': 'بہت اچھا',
    'star_excellent': 'بہترین',

    // Subscription
    'subscription_title': 'سبسکرپشن',
    'current_plan': 'موجودہ پلان',
    'available_plans': 'دستیاب پلانز',
    'change_plan': 'پلان تبدیل کریں',
    'switch_plan': 'پلان بدلیں',
    'best_value': 'بہترین قیمت',
    'current_badge': 'موجودہ',
    'active_renews': 'فعال · 8 اپریل 2026 کو تجدید',

    // Language
    'language_title': 'زبان',
    'apply': 'لاگو کریں',
    'language_set': 'زبان تبدیل کر دی گئی',

    // Role Selection
    'welcome_banner': 'ٹرانزٹ پرو میں خوش آمدید',
    'select_role': 'اپنا کردار منتخب کریں',
    'parent_label': 'میں والدین ہوں',
    'parent_desc': 'اپنے بچے کے اسکول کے سفر کی لائیو نگرانی کریں',
    'driver_label': 'میں ڈرائیور ہوں',
    'driver_desc': 'اپنے روٹ، طلباء اور روزانہ کے شیڈول کا انتظام کریں',
    'student_label': 'میں طالب علم ہوں',
    'student_desc':
        'بس کا شیڈول دیکھیں، اپنا سفر ٹریک کریں اور فیس کا انتظام کریں',
    'no_account': 'اکاؤنٹ نہیں ہے؟ ',
    'sign_up': 'سائن اپ کریں',
    'data_secure': 'آپ کا ڈیٹا محفوظ اور انکرپٹڈ ہے',

    // Login
    'back': 'واپس',
    'use_demo': 'ڈیمو اکاؤنٹ استعمال کریں',
    'email_address': 'ای میل ایڈریس',
    'email_hint': 'ای میل درج کریں',
    'password_lbl': 'پاس ورڈ',
    'password_hint': 'پاس ورڈ درج کریں',
    'forgot_password': 'پاس ورڈ بھول گئے؟',
    'login_encrypted': '256-bit انکرپٹڈ - GDPR کمپلائنٹ',
    'fill_fields_login': 'براہ کرم تمام خانے پُر کریں۔',
    'parent_login_title': 'والدین لاگ ان',
    'parent_login_sub': 'اپنے بچے کے سفر تک رسائی حاصل کریں',
    'driver_login_title': 'ڈرائیور لاگ ان',
    'driver_login_sub': 'آج کا روٹ شروع کریں',
    'student_login_title': 'طالب علم لاگ ان',
    'student_login_sub': 'اپنی بس اور حاضری ٹریک کریں',
    'signin_as_parent': 'بطور والدین سائن ان کریں؟',
    'signin_as_driver': 'بطور ڈرائیور سائن ان کریں؟',
    'signin_as_student': 'بطور طالب علم سائن ان کریں؟',
    'parent_role_name': 'والدین',
    'driver_role_name': 'ڈرائیور',
    'student_role_name': 'طالب علم',
    'parent_details_title': 'والدین کی تفصیلات',
    'driver_details_title': 'ڈرائیور کی تفصیلات',
    'student_details_title': 'طالب علم کی تفصیلات',

    // Signup
    'create_account': 'اکاؤنٹ بنائیں',
    'select_role_to_start': 'شروع کرنے کے لیے اپنا کردار منتخب کریں',
    'fill_info': 'نیچے اپنی معلومات فراہم کریں',
    'already_account': 'پہلے سے اکاؤنٹ ہے؟ ',
    'sign_in': 'سائن ان',
    'select_your_role_lbl': 'اپنا کردار منتخب کریں',
    'continue_btn': 'جاری رکھیں',
    'full_name_lbl': 'پورا نام',
    'enter_full_name': 'پورا نام درج کریں',
    'enter_email': 'ای میل درج کریں',
    'phone_lbl': 'فون نمبر',
    'enter_phone': 'اپنا فون نمبر درج کریں',
    'confirm_password_lbl': 'پاس ورڈ کی تصدیق',
    'create_password_hint': 'پاس ورڈ بنائیں',
    'reenter_password_hint': 'پاس ورڈ دوبارہ درج کریں',
    'agree_terms': 'میں سروس کی شرائط اور رازداری کی پالیسی سے اتفاق کرتا ہوں',
    'create_account_btn': 'اکاؤنٹ بنائیں',
    'add_another_child': 'ایک اور بچہ شامل کریں',
    'childs_name_lbl': 'بچے کا نام',
    'childs_name_hint': 'بچے کا پورا نام',
    'grade_level_lbl': 'کلاس / لیول',
    'select_level_hint': 'لیول منتخب کریں',
    'school_institution_lbl': 'اسکول / ادارہ',
    'license_number_lbl': 'لائسنس نمبر',
    'enter_license_hint': 'ڈرائیونگ لائسنس نمبر درج کریں',
    'vehicle_number_lbl': 'گاڑی کا نمبر',
    'vehicle_number_hint': 'مثلاً BUS-42',
    'vehicle_type_lbl': 'گاڑی کی قسم',
    'select_type_hint': 'قسم منتخب کریں',
    'experience_yrs_lbl': 'تجربہ (سال)',
    'student_id_lbl': 'اسٹوڈنٹ آئی ڈی',
    'student_id_hint': 'مثلاً STU-1234',
    'email_address_lbl': 'ای میل ایڈریس',
    'details_lbl': 'تفصیلات',
    'child_lbl': 'بچہ',
    'search_school_hint': 'اسکول / ادارہ تلاش کریں...',
    'experience_hint': 'مثلاً 5',

    // Forgot Password
    'forgot_password_title': 'پاس ورڈ بھول گئے؟',
    'check_email_title': 'ای میل چیک کریں',
    'forgot_pass_sub': 'ای میل درج کریں، ہم آپ کو ری سیٹ لنک بھیجیں گے',
    'check_email_sub': 'ہم نے آپ کی ای میل پر ری سیٹ لنک بھیج دیا ہے۔',
    'send_reset': 'ری سیٹ لنک بھیجیں',
    'reset_sent': 'ری سیٹ لنک کامیابی سے بھیج دیا گیا!',
    'back_to_login': 'لاگ ان پر واپس جائیں',

    // Welcome screen
    'safe_journeys': 'محفوظ سفر - خوش بچے - ذہنی سکون',
    'pill_tracking': 'لائیو ٹریکنگ',
    'pill_alerts': 'الرٹس',
    'pill_safe': 'محفوظ اور مامون',

    // Driver navbar
    'dnav_home': 'ہوم',
    'dnav_students': 'طلباء',
    'dnav_route': 'روٹ',
    'dnav_alerts': 'الرٹس',
    'dnav_profile': 'پروفائل',

    // Student navbar
    'snav_home': 'ہوم',
    'snav_track': 'ٹریک',
    'snav_schedule': 'شیڈول',
    'snav_qr': 'کیو آر پاس',
    'snav_fees': 'فیس',
    'snav_profile': 'پروفائل',

    // Driver dashboard
    'todays_route': 'آج کا روٹ',
    'in_progress_badge': 'جاری ہے',
    'not_started_badge': 'شروع نہیں ہوا',
    'route_progress': 'روٹ کی پیشرفت',
    'stops_done': 'اسٹاپس مکمل',
    'time_left': 'باقی وقت',
    'next_stop': 'اگلا اسٹاپ',
    'quick_actions': 'فوری اقدامات',
    'emergency': 'ہنگامی صورتحال',
    'alert_all': 'سب کو مطلع کریں',
    'share_location': 'لوکیشن شیئر کریں',
    'update_route': 'روٹ اپ ڈیٹ کریں',
    'todays_stats': 'آج کے اعداد و شمار',
    'students_picked': 'طلباء پک اپ کر لیے',
    'route_completion': 'روٹ کی تکمیل',
    'on_time_perf': 'وقت کی پابندی',
    'start_route': 'روٹ شروع کریں',
    'end_route': 'روٹ ختم کریں',

    // Driver attendance
    'student_attendance': 'طلباء کی حاضری',
    'boarding_progress': 'سوار ہونے کی پیشرفت',
    'boarded': 'سوار ہو گئے',
    'absent': 'غیر حاضر',
    'search_student': 'طالب علم یا اسٹاپ تلاش کریں...',

    // Driver route
    'route_navigator': 'روٹ نیویگیٹر',
    'live_route_map': 'لائیو روٹ میپ',
    'eta_school': 'اسکول پہنچنے کا وقت',
    'distance_left': 'باقی فاصلہ',
    'avg_speed': 'اوسط رفتار',

    // Driver notifications
    'messages': 'پیغامات',
    'parents_tab': 'والدین',
    'admin_tab': 'ایڈمن',
    'system_tab': 'سسٹم',
    'reply': 'جواب دیں',
    'type_reply': 'اپنا جواب لکھیں...',

    // Driver profile
    'driver_info_section': 'ڈرائیور کی معلومات',
    'license_no_lbl': 'لائسنس نمبر',
    'experience_lbl': 'تجربہ',
    'bus_number_lbl': 'بس نمبر',
    'route_lbl': 'روٹ',
    'mobile_lbl': 'موبائل',
    'total_students_lbl': 'کل طلباء',
    'bus_info_section': 'بس کی معلومات',
    'capacity_lbl': 'گنجائش',
    'fuel_lbl': 'فیول',
    'last_service_lbl': 'آخری سروس',
    'app_settings': 'ایپ سیٹنگز',
    'active_on_route': 'فعال - روٹ پر ہے',
    'settings': 'سیٹنگز',
    'share_loc_desc': 'والدین بس کی لوکیشن دیکھ سکتے ہیں',
    'parent_alerts_lbl': 'والدین کو خودکار الرٹس',
    'parent_alerts_desc': 'سوار ہونے کی اطلاع بھیجیں',
    'route_reminders_lbl': 'روٹ ریمائنڈرز',
    'route_reminders_desc': 'ہر اسٹاپ سے 10 منٹ پہلے',
    'break_alerts_lbl': 'بریک کی اطلاعات',
    'break_alerts_desc': 'شیڈول بریک کا الرٹ',
    'performance_report': 'کارکردگی کی رپورٹ',
    'performance_report_desc': '96% وقت کی پابندی',
    'documents_license': 'دستاویزات اور لائسنس',
    'documents_license_desc': 'تمام تصدیق شدہ',

    // Student dashboard
    'my_qr_pass': 'میرا کیو آر پاس',
    'show_qr': 'چیک ان/آؤٹ کے لیے کیو آر دکھائیں',
    'total_rides': 'کل سفر',

    // Student tracking
    'track_my_bus': 'میری بس ٹریک کریں',
    'live_map_view': 'لائیو میپ ویو',
    'gps_tracking_here': 'جی پی ایس ٹریکنگ یہاں نظر آئے گی',
    'distance': 'فاصلہ',
    'stops_left': 'باقی اسٹاپس',

    // Student schedule
    'my_schedule': 'میرا شیڈول',
    'pickup_dropoff_timings': 'پک اپ اور ڈراپ آف کے اوقات',
    'morning_pickup_s': 'صبح کا پک اپ',
    'be_at_stop': 'اسٹاپ پر پہنچیں',
    'bus_arrives': 'بس پہنچتی ہے',
    'qr_checkin': 'کیو آر چیک ان',
    'reach_school': 'اسکول پہنچیں',

    // Student attendance (QR)
    'qr_pass': 'کیو آر پاس',
    'show_pass_checkin': 'چیک ان اور چیک آؤٹ کے لیے دکھائیں',
    'monthly_report': 'ماہانہ رپورٹ',
    'total_checkins': 'کل\nچیک ان',

    // Student fees
    'my_fees_s': 'میری فیس',
    'fee_details_s': 'ٹرانسپورٹ فیس کی تفصیلات',
    'outstanding_balance_s': 'واجب الادا رقم',

    // Student profile
    'transport_details': 'ٹرانسپورٹ کی تفصیلات',
    'driver_phone_lbl': 'ڈرائیور فون',
    'parent_guardian_lbl': 'والدین / سرپرست',
    'bus_lbl': 'بس',
    'stop_lbl': 'اسٹاپ',
    'driver_lbl': 'ڈرائیور',
    'name_lbl': 'نام',
    'rides_lbl': 'سفر',
    'settings_lbl': 'سیٹنگز',
    'notifications_lbl': 'اطلاعات',
    'appearance_lbl': 'ظاہری شکل',
    'privacy_lbl': 'رازداری',
    'terms_lbl': 'شرائط و ضوابط',
    'log_out_text': 'لاگ آؤٹ',

    // FAQ
    'faq_q1': 'میں اپنے بچے کی بس کو ریئل ٹائم میں کیسے ٹریک کروں؟',
    'faq_a1':
        '"لائیو ٹریکنگ" ٹیب پر جائیں جو نچلے نیوی گیشن بار میں ہے۔ نقشہ بس کی موجودہ پوزیشن اور ہر اسٹاپ پر متوقع آمد کا وقت دکھائے گا۔',
    'faq_q2': 'میں اپنے اکاؤنٹ میں ایک اور بچہ کیسے شامل کروں؟',
    'faq_a2':
        'پروفائل ٹیب کھولیں، بچوں کے سیکشن تک اسکرول کریں، اور "+" بٹن پر کلک کریں۔ بچے کا نام، کلاس، اسکول اور بس کی تفصیلات درج کریں۔',
    'faq_q3': 'مجھے اطلاعات کیوں نہیں مل رہیں؟',
    'faq_a3':
        'یقینی بنائیں کہ آپ کے ڈیوائس کی سیٹنگز میں ٹرانزٹ پرو کی اطلاعات فعال ہیں۔ آپ پروفائل ٹیب پر ایپ سیٹنگز میں الرٹ ترجیحات بھی چیک کر سکتے ہیں۔',
    'faq_q4': 'میں اپنے بچے کا بس روٹ کیسے اپ ڈیٹ کروں؟',
    'faq_a4':
        'پروفائل ٹیب پر بچے کے کارڈ پر کلک کریں، پھر "معلومات تبدیل کریں" منتخب کریں۔ بس نمبر، روٹ یا اسٹاپ کے خانے اپ ڈیٹ کریں اور محفوظ کریں۔',
    'faq_q5': 'میں اپنے ہنگامی رابطے کیسے تبدیل کروں؟',
    'faq_a5':
        'پروفائل → ہنگامی رابطے پر جائیں۔ وہاں سے آپ رابطے شامل، تبدیل یا حذف کر سکتے ہیں۔',
    'faq_q6': 'پریمیم پلان میں کیا شامل ہے؟',
    'faq_a6':
        'پریمیم میں لائیو GPS ٹریکنگ، 3 بچوں کے پروفائل، پش اور SMS الرٹس، مکمل سفر کی تاریخ اور ہنگامی رابطوں کا انتظام شامل ہے۔',

    // Subscription plan features
    'plan_premium_name': 'پریمیم',
    'plan_family_name': 'فیملی',
    'plan_basic_name': 'بیسک',
    'feat_live_gps': 'لائیو GPS ٹریکنگ',
    'feat_3_profiles': '3 بچوں کے پروفائل',
    'feat_push_sms': 'پش + SMS الرٹس',
    'feat_trip_history': 'مکمل سفر کی تاریخ',
    'feat_emergency': 'ہنگامی رابطے',
    'feat_everything_premium': 'پریمیم کی تمام سہولیات',
    'feat_unlimited_profiles': 'لامحدود بچوں کے پروفائل',
    'feat_priority_support': 'ترجیحی سپورٹ',
    'feat_route_custom': 'روٹ کی حسب ضرورت تبدیلی',
    'feat_driver_chat': 'ڈرائیور سے براہ راست چیٹ',

    // Trip history
    'trip_type_morning_pickup': 'صبح کی سواری',
    'trip_type_afternoon_dropoff': 'دوپہر کی واپسی',
    'trip_status_on_time': 'وقت پر',
    'trip_status_5_late': '5 منٹ دیر',
    'trip_status_1_early': '1 منٹ جلدی',
    'trip_to_arrow': '←',

    // Payment screens
    'select_payment_method': 'ادائیگی کا طریقہ منتخب کریں',
    'amount_due': 'واجب الادا رقم',
    'month_lbl': 'مہینہ',
    'choose_method': 'ادائیگی کا طریقہ چنیں',
    'cash_payment': 'نقد ادائیگی',
    'cash_payment_desc': 'ڈرائیور کو نقد دیں اور تصدیق کی درخواست جما کریں۔',
    'requires_approval': 'ڈرائیور کی تصدیق ضروری',
    'online_payment': 'آنلائن ٹرانسفر',
    'online_payment_desc':
        'ڈرائیور کے اکاؤنٹ میں جاز کیش یا آسان پیسہ سے ٹرانسفر کریں۔',
    'card_payment': 'کریڈٹ / ڈیبٹ کارڈ',
    'card_payment_desc': 'ویزا یا ماسٹر کارڈ سے محفوظ طریقے سے ادا کریں۔',
    'secure_payment_note': 'تمام ادائیگیاں محفوظ ہیں۔',
    'cash_info_banner':
        'ڈرائیور کو بالکل رقم دیں۔ درخواست جما کرنے کے بعد ڈرائیور اپنی ایپ پر تصدیق کرے گا۔',
    'notes_optional': 'نوٹس (اختیاری)',
    'cash_notes_hint': 'مثلاً سکول گیٹ پر 14 دسمبر کو ادا کیا...',
    'send_cash_request': 'نقد ادائیگی کی درخواست بھیجیں',
    'request_submitted': 'درخواست جما ہو گئی!',
    'cash_request_submitted_desc':
        'آپ کے ڈرائیور کو اطلاع دے دی گئی ہے۔ نقد دینے پر وہ تصدیق کریں گے۔',
    'amount_lbl': 'رقم',
    'request_id_lbl': 'درخواست نمبر',
    'status_lbl': 'حیثیت',
    'pending_driver_confirmation': 'ڈرائیور کی تصدیق زیر انتظار',
    'back_to_fees': 'فیس پیج پر واپس',
    'payment_method_lbl': 'طریقہ',
    'select_child': 'بچہ منتخب کریں',
    'select_platform': 'پلیٹ فارم منتخب کریں',
    'driver_account_details': 'ڈرائیور اکاؤنٹ کی تفصیل',
    'platform_not_available':
        'یہ پلیٹ فارم آپ کے ڈرائیور کے لیے دستیاب نہیں۔ دوسرا طریقہ استعمال کریں۔',
    'enter_transaction_id': 'ٹرانزیکشن آئی ڈی درج کریں',
    'txn_id_hint': 'مثلاً TXN1234567890',
    'confirm_payment': 'میں نے ادا کر دیا — تصدیق کریں',
    'payment_submitted': 'ادائیگی جما ہو گئی!',
    'online_submitted_desc':
        'آپ کا ٹرانزیکشن ریکارڈ ہو گیا۔ ڈرائیور تصدیق کرے گا۔',
    'transaction_id_lbl': 'ٹرانزیکشن آئی ڈی',
    'platform_lbl': 'پلیٹ فارم',
    'driver_account': 'ڈرائیور اکاؤنٹ',
    'driver_name_lbl': 'ڈرائیور',
    'account_name_lbl': 'اکاؤنٹ کا نام',
    'account_number_lbl': 'اکاؤنٹ نمبر',
    'bus_lbl': 'بس',
    'send_exactly': 'بالکل یہ رقم بھیجیں:',
    'copied': 'کاپی ہو گیا!',
    'card_number_lbl': 'کارڈ نمبر',
    'expiry_lbl': 'میعاد ختم',
    'cvv_lbl': 'CVV',
    'cardholder_name': 'کارڈ ہولڈر کا نام',
    'name_on_card_hint': 'بالکل ویسے جیسے کارڈ پر لکھا ہو',
    'invalid_card_number': 'صحیح 16 ہندسے کا کارڈ نمبر درج کریں',
    'invalid_expiry': 'صحیح میعاد درج کریں (MM/YY)',
    'invalid_cvv': 'صحیح CVV درج کریں',
    'enter_card_name': 'کارڈ ہولڈر کا نام درج کریں',
    'processing': 'پروسیس ہو رہی ہے...',
    'pay': 'ادا کریں',
    'ssl_secured': 'SSL اینکریپٹڈ · 256-بٹ سیکیورٹی',
    'payment_successful': 'ادائیگی کامیاب!',
    'card_success_desc': 'آپ کی ادائیگی کامیابی سے مکمل ہو گئی۔',
    'card_lbl': 'کارڈ',
    'approved': 'منظور ہو گیا',
    'amount_to_pay': 'ادا کی جانے والی رقم',
    'card_name_lbl': 'کارڈ ہولڈر',
  };
}
