// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCY65RR8T7O2ghVmQDfrBClWL8RctWGgqE',
    appId: '1:231263449779:web:12e9bb6b22a9f0a52f76c6',
    messagingSenderId: '231263449779',
    projectId: 'transitpro-db',
    authDomain: 'transitpro-db.firebaseapp.com',
    storageBucket: 'transitpro-db.firebasestorage.app',
    measurementId: 'G-6XW9QGWRY6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVqe3a87m5AgLg7frpYcx8Yid37EI0n8U',
    appId: '1:231263449779:android:140f82afb54519da2f76c6',
    messagingSenderId: '231263449779',
    projectId: 'transitpro-db',
    storageBucket: 'transitpro-db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBldH6EDtO4pEb9mRH7CfRvaP_SYpd3sH4',
    appId: '1:231263449779:ios:442d1b9bd602114a2f76c6',
    messagingSenderId: '231263449779',
    projectId: 'transitpro-db',
    storageBucket: 'transitpro-db.firebasestorage.app',
    iosBundleId: 'com.example.transitPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBldH6EDtO4pEb9mRH7CfRvaP_SYpd3sH4',
    appId: '1:231263449779:ios:442d1b9bd602114a2f76c6',
    messagingSenderId: '231263449779',
    projectId: 'transitpro-db',
    storageBucket: 'transitpro-db.firebasestorage.app',
    iosBundleId: 'com.example.transitPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCY65RR8T7O2ghVmQDfrBClWL8RctWGgqE',
    appId: '1:231263449779:web:c9924618ca82fef12f76c6',
    messagingSenderId: '231263449779',
    projectId: 'transitpro-db',
    authDomain: 'transitpro-db.firebaseapp.com',
    storageBucket: 'transitpro-db.firebasestorage.app',
    measurementId: 'G-RKFLV5ZK9W',
  );
}
